function createfigure2(X1,YMatrix1,X2,YMatrix2,X3,YMatrix3)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 09-Nov-2022 18:15:12

% Create figure
figure1 = figure('Name','2','Position',[0,40,560,400]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1,X2,YMatrix2,X3,YMatrix3,'LineWidth',1,'Parent',axes1);
set(plot1(1),'Color',[0 0 0]);
set(plot1(2),'Marker','*','LineStyle','--','Color',[0 0 1]);
set(plot1(3),'Marker','square','LineStyle','-.','Color',[1 0 0]);

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1(1),3251.513671875,-3.97970641005436);
% Create datatip
datatip(plot1(1),'DataIndex',152);

% Create ylabel
ylabel('|H|, dB','FontSize',16);

% Create xlabel
xlabel('f, kHz','FontSize',16);

% Create title
title('Filter numbers: №1,№2,№3','FontSize',16);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 21000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-60 10]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'XTick',[2000 8000 16000],'XTickLabel',{'2 kHz','8 kHz','16 kHz'});
% Create legend
legend(axes1,'show');

